### ISSUE TITLE
/Users/travis in my build-log - how is it possible?

### ISSUE THREAD

**Issue by fzzr-** [three-rs/three#173]
I [didn't find](https://github.com/three-rs/three/search?utf8=✓&q=travis&type=) how and why.

```log
git clone https://github.com/three-rs/three.git; cd three
...
cargo run --example tutorial
...
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/tutorial`
thread 'main' panicked at 'gl function was not loaded', /Users/ak/Developer/Projects/rusthell/three/target/debug/build/gfx_gl-5792be931b48f6be/out/gl_bindings.rs:1506:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:381
   3: std::panicking::default_hook
             at libstd/panicking.rs:397
   4: std::panicking::begin_panic
             at libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:538
   6: gfx_gl::missing_fn_panic
             at ./target/debug/build/gfx_gl-5792be931b48f6be/out/gl_bindings.rs:1506
   7: gfx_gl::Gl::DrawArraysInstancedBaseInstance
             at ./target/debug/build/gfx_gl-5792be931b48f6be/out/gl_bindings.rs:3573
   8: gfx_device_gl::Device::process
             at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.0/src/lib.rs:667
   9: gfx_device_gl::Device::no_fence_submit
             at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.0/src/lib.rs:815
  10: gfx_device_gl::Device::track_mapped_gpu_access
             at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.0/src/lib.rs:937
  11: <gfx::encoder::Encoder<R, C>>::flush_no_reset
             at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:197
  12: <gfx::encoder::Encoder<R, C>>::flush
             at /Users/ak/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:188
  13: three::render::Renderer::resize
             at src/render/mod.rs:975
  14: three::util::hash_f32_slice
             at src/window.rs:235
  15: tutorial::main
             at examples/tutorial.rs:26
  16: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  17: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:480
  18: backtrace_vector_release
             at libpanic_unwind/lib.rs:102
  19: std::sys_common::gnu::libbacktrace::init_state
             at libstd/panicking.rs:459
             at libstd/panic.rs:365
             at libstd/rt.rs:58
  20: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  21: tutorial::main
```

See lines with `/Users/travis/build/rust-lang/rust/...`.

- - -

#### My Env:

macOS: 10.12.6 (16G1036)
```log
rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

installed targets for active toolchain
--------------------------------------

aarch64-apple-ios
armv7-apple-ios
armv7s-apple-ios
i386-apple-ios
x86_64-apple-darwin
x86_64-apple-ios

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.25.0-nightly (b5392f545 2018-01-08)
```

**Comment by fzzr-** [comment]
And since I'm here, one more question:

What is `missing_fn` in the `6: gfx_gl::missing_fn_panic`? What I missing?

**Comment by vitvakatu** [comment]
I'm not exactly sure what's `User/travis`, but it seems like your GPU driver doesn't support something that we use. Can you try [gfx examples(pre-ll branch)](https://github.com/gfx-rs/gfx/tree/pre-ll/examples)?

**Comment by kvark** [comment]
Might be related to https://gitter.im/gfx-rs/gfx?at=5a55ef76232e79134deb6947

**Comment by kvark** [comment]
> @kvark - woah - that is an old version. You'll probably want to be on v0.8.0 of gl_generator. Fixes some problems with enums being incorrectly optimized out.
Dzmitry Malyshau
@kvark
Jan 10 05:47
@brendanzab thanks for the heads up!
Brendan Zabarauskas
@brendanzab
Jan 10 05:48
Apparently it caused the servo folks some grief trying to track it down! https://github.com/brendanzab/gl-rs/pull/444#issuecomment-356551783
Not sure when the optimisations tick over to stable, but if you see bug reports related to function pointers not being loaded, that's why.

**Comment by fzzr-** [comment]
> I'm not exactly sure what's User/travis, but it seems like your GPU driver doesn't support something that we use.

```
NVIDIA GeForce 320M 256 MB
Model Name:	MacBook Air
Model Identifier:	MacBookAir3,2
Processor Name:	Intel Core 2 Duo
Processor Speed:	2.13 GHz
Number of Processors:	1
Total Number of Cores:	2
Memory:	4 GB
```
[OGL Renderer Info.txt](https://github.com/three-rs/three/files/1624004/OGL.Renderer.Info.txt)

- - -

> Can you try gfx examples(pre-ll branch)?

Thx! __It's much better result, but app isn't responding and I see panic in the execution-log.__

```
    Finished dev [unoptimized + debuginfo] target(s) in 355.17 secs
     Running `target/debug/examples/cube`
thread 'main' panicked at 'Error InvalidFramebufferOperation executing command: Clear(Some(Float([0.1, 0.2, 0.3, 1.0])), None, None)', src/backend/gl/src/lib.rs:808:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Avg frame time: 42.16827852998066 ms
```
[gfx-cube-execution-log.txt](https://github.com/three-rs/three/files/1624029/gfx-cube-log.txt)
![screen shot 2018-01-11 at 23 32 56](https://user-images.githubusercontent.com/888526/34846157-4f8b1462-f728-11e7-9830-7111de2ad278.png)

I see the cube but something wrong... :(

- - -

For example on my setup `rust-sdl2` works good with automatically (i think so) selected OpenGL render.
![screen shot 2018-01-11 at 23 29 32](https://user-images.githubusercontent.com/888526/34845897-83a6a262-f727-11e7-8c72-e3dbc8ab6da6.png)

**Comment by fzzr-** [comment]
Very strange behaviour... I can't reproduce any error in the Cube example.
![screen shot 2018-01-11 at 23 44 41](https://user-images.githubusercontent.com/888526/34846575-9a69ea20-f729-11e7-90fc-6ab6e22917a7.png)


So I think it works. Thank you!

And what you think about user Travis? I really have no idea. Maybe it from rustup or cargo or any else...

**Comment by fzzr-** [comment]
And `terrain_tessellated` example crashing with: 
```log
   9: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  11: <terrain_tessellated::App<R> as gfx_app::Application<R>>::new
```
full log: [gfx-terrain_tessellated.log.txt](https://github.com/three-rs/three/files/1624211/gfx-terrain_tessellated.log.txt)

**Comment by fzzr-** [comment]
And `performance` example GL vs. GFX:
[gfx-performance.txt](https://github.com/three-rs/three/files/1624217/gfx-performance.txt)

**Comment by kvark** [comment]
@fzzr- Thank you for taking time gathering all that info, it's invaluable for us to address the issues you found (and looks like you found a whole lot of stuff). Most of those should be forwarded to issues on gfx-rs (pre-ll) side of things.

> I didn't find how and why.

I don't think that's important. Basically, the call stack prints the paths from which the source was built with debug info. Since you didn't build `libstd` and just downloaded the binaries (via `rustup`), it shows the paths from the machine where it was built.

> What is missing_fn in the 6: gfx_gl::missing_fn_panic? What am I missing?

The call stack has `DrawArraysInstancedBaseInstance`, so that's what's missing, I suppose. We may  not be performing the check for the GL version/extension correctly for this function in GL backend. That's a bug!

> NVIDIA GeForce 320M 256 MB

Your GL version is totally fine and should be fully supported. In fact, my Mac Mini 2010 has a similar configuration, so I can confirm. The cube runs fine there though...

> Very strange behaviour... I can't reproduce any error in the Cube example.

Wait, so now you aren't getting the error? Would be great to have a repro case.

> Another issue found. In the any example with movement, the movement happening only when I moving mouse-cursor or app getting an any keyboard event.

Yeah, that's me screwing things up :/ I used glutin's [run_forever](https://docs.rs/glutin/0.12.0/glutin/struct.EventsLoop.html#method.run_forever) method in the `gfx_app` in order to be Emscripten-compatible, but I didn't realize that it stops auto-refreshing. Ideas are welcome! Needs to be filed officially on gfx-rs repo regardless.

> And terrain_tessellated example crashing with:

Tessellation is not supported on your machine (with GL), but we should be failing with a proper error message, hence - it's another bug. I can totally repro it on my machine.

> And performance example GL vs. GFX:

Seem to work fine. If you are concerned about the numbers, better build with `--release` ;)

**Comment by fzzr-** [comment]
Just now I tried [ggez](https://github.com/ggez/ggez) `master` branch and `cargo run --example astroblasto` - it works! And it using:
```toml
gfx = "0.16"
gfx_device_gl = "0.14"
gfx_window_sdl = "0.7"
```

**Comment by kvark** [comment]
I suppose this issue can be closed. Things to fix upstream in gfx-rs and such don't need to be tracked here.
