### ISSUE TITLE
`keys_hit()` does not properly report deltas

### ISSUE THREAD

**Issue by kbarros** [three-rs/three#187]
I put the following print statements inside my main event loop:

```rust
println!("{:?} {:?}",
    win.input.keys_hit().contains(&three::controls::Key::LWin), 
    win.input.keys_hit().contains(&three::controls::Key::Q));
```

If I press and hold the "LWin" button, I get only a single `true` printout. However, if I press and hold the "Q" button I get a `true` printout every iteration in the event loop. Is this expected behavior? What's the easiest way to get the `Delta` for "Q" presses?

I'm on MacOS.

**Comment by vitvakatu** [comment]
I'm starting to think that our input system requires some improvements again. :confused: 

It looks like desired behavior for me, as `keys_hit` contains only keys that were hit in the current frame. The difference between LWin and Q can be easily explained, as your OS can emit "key down" either on every frame or only once, at first hit. 

`Delta` is unimplemented for `Key` by design, as the key can be pressed or not, there's no "delta" in this.

**Comment by kbarros** [comment]
How would I take an action when the "Q" key is first pressed, but ignore
"Q" hit events in subsequent frames, while the "Q" button is still being
held down? In other words, get notified only of the "key press" event?

**Comment by vitvakatu** [comment]
Well, it makes sense. I've found the way to patch input, will prepare a PR soon.
